# Generated by Django 5.2.12 on 2026-06-09 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Semana 15 - Abril', max_length=200)),
                ('fecha_inicio', models.DateField(help_text='Viernes')),
                ('fecha_fin', models.DateField(help_text='Jueves')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_fijo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_destajos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bonos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Nomina.nomina')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('asistencia', models.BooleanField(default=True)),
                ('cajas_hechas', models.IntegerField(default=0)),
                ('procesos_hechos', models.IntegerField(default=0)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_diarios', to='Empleados.empleados')),
            ],
            options={
                'verbose_name': 'Registro de Trabajo Diario',
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
