# Generated by Django 5.2.12 on 2026-06-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Semana 15 - Abril', max_length=200)),
                ('fecha_inicio', models.DateField(help_text='Viernes')),
                ('fecha_fin', models.DateField(help_text='Jueves')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_fijo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_destajos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bonos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleados')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Nomina.nomina')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_evento', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Salida'), (4, 'Entrada Almuerzo'), (5, 'Salida Almuerzo')], default=0)),
                ('uid_reloj', models.IntegerField(unique=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='Empleados.empleados')),
            ],
        ),
    ]
