# Generated by Django 5.2.12 on 2026-06-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_empleados_id_reloj_checador'),
        ('Nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_evento', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Salida'), (4, 'Entrada Almuerzo'), (5, 'Salida Almuerzo')], default=0)),
                ('uid_reloj', models.IntegerField(unique=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='Empleados.empleados')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroTrabajo',
        ),
    ]
