# Generated by Django 5.2.12 on 2026-06-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_empleados', models.IntegerField(default=0)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('salarioDiario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('nss', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc', models.CharField(blank=True, max_length=50, null=True)),
                ('statusImss', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cellular', models.CharField(blank=True, max_length=20, null=True)),
                ('usuaio', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('dias_vacaciones', models.IntegerField(default=0)),
                ('jornada_laboral', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonoEmergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('avisarA', models.CharField(blank=True, max_length=100, null=True)),
                ('isSupervisor', models.BooleanField(default=False)),
                ('id_reloj_checador', models.IntegerField(blank=True, null=True, unique=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.departamento')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='Empleados.empleados')),
                ('puesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.puesto')),
            ],
        ),
    ]
