# Generated by Django 5.2.12 on 2026-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='isSupervisor',
            field=models.BooleanField(default=False),
        ),
    ]
