# Generated by Django 5.2.12 on 2026-06-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_empleados_issupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.departamento'),
        ),
    ]
