# Generated by Django 5.2.12 on 2026-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_puesto_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='id_reloj_checador',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
