# Generated by Django 5.2.12 on 2026-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='lote_origen',
            field=models.CharField(blank=True, help_text='Lote del cual proviene (ej: Materia Prima)', max_length=50, null=True),
        ),
    ]
