# Generated by Django 5.2.12 on 2026-06-09 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0002_remove_almacen_categoria_remove_almacen_precio_and_more'),
        ('Proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='proveedor',
            field=models.ManyToManyField(blank=True, to='Proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
