# Generated by Django 5.2.12 on 2026-07-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0002_movimiento_lote_origen'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='destino_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='destino_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='origen_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='origen_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
