# Generated by Django 5.2.12 on 2026-06-09 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0003_movimientos_proveedor_movimientos_usuario'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proveedores.proveedor'),
        ),
    ]
