# Generated by Django 5.2.12 on 2026-06-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0004_remove_movimientos_proveedor_movimientos_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='enFactura',
            field=models.BooleanField(default=False),
        ),
    ]
