# Generated by Django 5.2.12 on 2026-06-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_cliente',
            name='movimiento',
            field=models.ManyToManyField(blank=True, to='Inventarios.movimientos'),
        ),
        migrations.AddField(
            model_name='pago_cliente',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.factura_cliente'),
        ),
    ]
