# Generated by Django 5.2.12 on 2026-07-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0003_alter_movimiento_destino_content_type_and_more'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, help_text='Días de crédito asignados'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de factura o serie del proveedor', max_length=50)),
                ('uuid', models.UUIDField(blank=True, help_text='Folio Fiscal (UUID) del SAT', null=True, unique=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('fecha', models.DateField(help_text='Fecha de emisión de la factura')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite de pago', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIAL', 'Pagada Parcialmente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, help_text='Cuánto se debe aún de esta factura', max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventarios.concepto')),
                ('movimientos', models.ManyToManyField(blank=True, to='Inventarios.movimiento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedor')),
            ],
            options={
                'unique_together': {('proveedor', 'numero')},
            },
        ),
    ]
