# Generated by Django 5.2.12 on 2026-07-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_proveedor_dias_credito_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=12)),
                ('metodo_pago', models.CharField(help_text='Método de pago utilizado (Transferencia, Cheque, Efectivo, etc.)', max_length=50)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia o folio del pago', max_length=100, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Proveedores.factura')),
            ],
        ),
    ]
